<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Agents.AI" Version="1.22.0" />
    <PackageReference Include="Microsoft.Extensions.AI" Version="10.10.0" />
    <PackageReference Include="Microsoft.Extensions.AI.OpenAI" Version="10.10.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="11.0.0-rc.1.26425.128" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.12" />
    <PackageReference Include="OllamaSharp" Version="5.4.30" />
    <PackageReference Include="OpenAI" Version="2.14.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ArchMind.Application\ArchMind.Application.csproj" />
    <ProjectReference Include="..\ArchMind.Domain\ArchMind.Domain.csproj" />
  </ItemGroup>

</Project>
